apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice
  namespace: service01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice
  template:
    metadata:
      labels:
        app: myservice
    spec:
      containers:
        - image: leffen/myservice
          name: myservice
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          env:
          - name: BACKGROUND_COLOR
            value: cyan
